databases:
  - name: tutoring
    databaseName: tutoring
    user: tutoring

services:
  - type: web
    name: tutoring
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tutoring
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
